// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qecpkbafqpyvmuattmaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlY3BrYmFmcXB5dm11YXR0bWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTQ3OTgsImV4cCI6MjA2MzQzMDc5OH0.DCiC66K2VS5wJG-r9NEwXkWai8UX7K7hRg3htrRaBAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);